// ============================================================
// THE CODEX OF GIZA — MODEL CONVERTER (tools/convert_models.js)
//
// Turns a downloaded character or prop (.fbx / .glb / .gltf) into a
// compact .glb the game can use, and packs it into models/<name>.js so it
// loads both from a double-clicked index.html (file://) and on GitHub
// Pages. Runs the real three.js loaders/exporter inside headless Chrome.
//
//   node tools/convert_models.js <name> <input> [options]
//     --anim clipName=path/to/anim.fbx   add a Mixamo animation (repeatable;
//                                        "without skin" downloads are smallest)
//     --inplace                          strip forward root motion from clips
//                                        (the game moves characters itself)
//     --tex 1024                         max texture size (default 1024)
//     --copy                             pack a .glb as-is (no re-export)
//
// Needs Node and Playwright (npm i playwright) with Chrome installed.
// ============================================================
const fs = require('fs');
const path = require('path');
let chromium;
try { ({ chromium } = require('playwright')); }
catch (e) { console.error('Playwright is needed: npm i playwright'); process.exit(1); }

const ROOT = path.join(__dirname, '..');
const args = process.argv.slice(2);
const name = args[0], input = args[1];
if (!name || !input) { console.error('usage: node tools/convert_models.js <name> <input> [--anim clip=file.fbx] [--inplace] [--tex 1024] [--copy]'); process.exit(1); }
const anims = [];
let inplace = false, tex = 1024, copy = false;
for (let i = 2; i < args.length; i++) {
    if (args[i] === '--anim') { const [c, f] = args[++i].split('='); anims.push({ clip: c, file: f }); }
    else if (args[i] === '--inplace') inplace = true;
    else if (args[i] === '--tex') tex = +args[++i];
    else if (args[i] === '--copy') copy = true;
}

function writeOut(glbBuf) {
    const dir = path.join(ROOT, 'models');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, name + '.glb'), glbBuf);
    const js = '// generated by tools/convert_models.js — do not edit\n' +
        '(window.CODEX_MODELS = window.CODEX_MODELS || {})[' + JSON.stringify(name) + '] = "' + glbBuf.toString('base64') + '";\n';
    fs.writeFileSync(path.join(dir, name + '.js'), js);
    console.log(`wrote models/${name}.glb (${(glbBuf.length / 1e6).toFixed(2)} MB) and models/${name}.js`);
}

(async () => {
    if (copy) { writeOut(fs.readFileSync(input)); return; }
    const b = await chromium.launch({ channel: 'chrome' });
    const p = await b.newPage();
    p.on('console', m => { if (m.type() === 'error') console.log('  [page] ' + m.text().slice(0, 200)); });
    await p.goto('about:blank');
    for (const f of ['three.min.js', 'fflate.min.js', 'NURBSUtils.js', 'NURBSCurve.js', 'FBXLoader.js', 'GLTFLoader.js', 'GLTFExporter.js'])
        await p.addScriptTag({ path: path.join(ROOT, 'lib', f) });
    const ext = path.extname(input).slice(1).toLowerCase();
    const job = {
        ext, data: fs.readFileSync(input).toString('base64'), tex, inplace,
        anims: anims.map(a => ({ clip: a.clip, data: fs.readFileSync(a.file).toString('base64') })),
    };
    const out = await p.evaluate(async (job) => {
        const ab = (b64) => { const s = atob(b64), u = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) u[i] = s.charCodeAt(i); return u.buffer; };
        const parse = async (ext, buf) => {
            if (ext === 'fbx') { const r = new THREE.FBXLoader().parse(buf, ''); return { root: r, clips: r.animations || [] }; }
            const g = await new Promise((res, rej) => new THREE.GLTFLoader().parse(buf, '', res, rej));
            return { root: g.scene, clips: g.animations || [] };
        };
        const { root, clips } = await parse(job.ext, ab(job.data));
        for (const a of job.anims) {
            const r = await parse('fbx', ab(a.data));
            if (r.clips[0]) { r.clips[0].name = a.clip; clips.push(r.clips[0]); }
        }
        // wait for embedded textures to decode (the loader fills texture.image in later)
        const MAPS = ['map', 'normalMap', 'emissiveMap', 'roughnessMap', 'metalnessMap', 'aoMap', 'alphaMap', 'bumpMap', 'specularMap'];
        const texes = [];
        root.traverse(o => { if (o.material) [].concat(o.material).forEach(m => { for (const k of MAPS) if (m[k]) texes.push(m[k]); }); });
        const ready = t => t.image && (t.image.naturalWidth || t.image.width) && t.image.complete !== false;
        for (let waited = 0; waited < 20000 && !texes.every(ready); waited += 100) await new Promise(r => setTimeout(r, 100));
        let dropped = 0;
        root.traverse(o => { if (o.material) [].concat(o.material).forEach(m => { for (const k of MAPS) if (m[k] && !ready(m[k])) { m[k] = null; dropped++; } }); });
        if (dropped) console.error('dropped ' + dropped + ' texture(s) that never loaded');
        // Phong/Lambert → Standard (what glTF understands), JPEG where there's no alpha
        root.traverse(o => {
            if (!o.isMesh) return;
            const conv = [].concat(o.material).map(m => {
                const s = m.isMeshStandardMaterial ? m : new THREE.MeshStandardMaterial({
                    name: m.name, color: m.color, map: m.map || null, normalMap: m.normalMap || null,
                    emissive: m.emissive, emissiveMap: m.emissiveMap || null,
                    transparent: !!m.transparent, opacity: m.opacity, alphaTest: m.alphaTest || 0,
                    side: m.side, roughness: 0.85, metalness: 0,
                });
                for (const k of ['map', 'normalMap', 'emissiveMap']) if (s[k]) s[k].userData.mimeType = s.transparent && k === 'map' ? 'image/png' : 'image/jpeg';
                return s;
            });
            o.material = conv.length === 1 ? conv[0] : conv;
        });
        // walk in place: flatten the hips' horizontal travel
        if (job.inplace) for (const c of clips) for (const t of c.tracks) {
            if (!/hips.*\.position$/i.test(t.name)) continue;
            const v = t.values, x0 = v[0], z0 = v[2];
            for (let i = 0; i < v.length; i += 3) { v[i] = x0; v[i + 2] = z0; }
        }
        const info = { clips: clips.map(c => c.name + ' ' + c.duration.toFixed(2) + 's'), meshes: 0, bones: 0, box: null };
        root.traverse(o => { if (o.isMesh) info.meshes++; if (o.isBone) info.bones++; });
        const box = new THREE.Box3().setFromObject(root); const sz = box.getSize(new THREE.Vector3());
        info.box = [sz.x, sz.y, sz.z].map(n => +n.toFixed(2));
        const glb = await new Promise((res, rej) => new THREE.GLTFExporter().parse(root, res, rej, { binary: true, animations: clips, maxTextureSize: job.tex, onlyVisible: false }));
        const u = new Uint8Array(glb); let s = '';
        for (let i = 0; i < u.length; i += 0x8000) s += String.fromCharCode.apply(null, u.subarray(i, i + 0x8000));
        return { b64: btoa(s), info };
    }, job);
    console.log('clips:', out.info.clips.join(', ') || '(none)', '| meshes', out.info.meshes, '| bones', out.info.bones, '| size', out.info.box.join(' x '));
    writeOut(Buffer.from(out.b64, 'base64'));
    await b.close();
})().catch(e => { console.error('FAILED', e.message); process.exit(1); });
