// ============================================================
// EXPORT THE CHAPTER 1 MAP FOR THE POKE-STYLE BUILD (tools/export_poke_map.js)
// Boots the 3D game headless and writes poke/map_ch1.js: the same camp,
// as data the pixel version can draw — every object (place, size, label,
// what it says when examined), the collision walls, the roads and rail,
// the named places, and a terrain grid (one cell per tile).
//
//   node tools/export_poke_map.js
// Needs Node and Playwright (npm i playwright) with Chrome installed.
// ============================================================
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const ROOT = path.join(__dirname, '..');
const TILE_U = 64;     // world units per 32-px tile (2 m: a building is a handful of tiles, like the DS games)

(async () => {
    const b = await chromium.launch({ channel: 'chrome' });
    const p = await b.newPage();
    await p.goto('file:///' + path.join(ROOT, 'index.html').replace(/\\/g, '/').replace(/ /g, '%20'));
    await p.waitForFunction(() => window.BOOT_3D_OK === true, null, { timeout: 120000 });
    const data = await p.evaluate((TILE_U) => {
        resetGameState(); startGame();
        for (let i = 0; i < 40 && gameState.isDialogueActive; i++) closeDialogue();
        const R = Math.round;
        const L = CH1_LAYOUT;
        // what each thing says when you first look at it (arrival state)
        const say = (id) => {
            const sc = id && storyData[id];
            if (!sc) return null;
            try {
                const speaker = typeof sc.speaker === 'function' ? sc.speaker() : sc.speaker;
                const text = typeof sc.text === 'function' ? sc.text() : sc.text;
                return text ? [speaker || 'System', String(text)] : null;
            } catch (e) { return null; }
        };
        const objects = mapObjects[1].map(o => ({
            id: o.id, label: o.label, model: (o.modelLabel || o.label || '').toLowerCase(),
            x: R(o.x), y: R(o.y), w: R(o.w), h: R(o.h), scene: o.interactScene || null, say: say(o.interactScene),
            deco: !!o.decorative, built: !!CH1_BUILDERS[o.id],
        }));
        const walls = mapWalls[1].map(w => ({ x: R(w.x), y: R(w.y), w: R(w.w), h: R(w.h), k: w.kind || '' }));
        // terrain grid: per tile — height, path (0 none, 1 worn, 2 road, 3 wheel rut), rock, wadi, outside, trench
        const gw = Math.ceil(L.W / TILE_U), gh = Math.ceil(L.H / TILE_U);
        const hgt = [], path = [], rock = [], wadi = [], out = [], dip = [];
        for (let j = 0; j < gh; j++) for (let i = 0; i < gw; i++) {
            const x = (i + 0.5) * TILE_U, z = (j + 0.5) * TILE_U;
            const h = ch1HeightBase(x, z);
            hgt.push(R(h));
            const [pm, kind] = ch1PathMask(x, z);
            path.push(pm > 0.45 ? (kind === 2 ? 3 : kind === 1 ? 2 : 1) : 0);
            const e = 12, sx = ch1HeightBase(x + e, z) - ch1HeightBase(x - e, z), sz = ch1HeightBase(x, z + e) - ch1HeightBase(x, z - e);
            rock.push(Math.hypot(sx, sz) / (2 * e) > 0.55 ? 1 : 0);
            wadi.push(ch1WadiDist(x, z) < 70 ? 1 : 0);
            out.push(ch1BoundaryOut(x, z) > 0 ? 1 : 0);
            dip.push(ch1TrenchDip(x, z) > 6 ? 1 : 0);
        }
        // the rooms you can walk into: what's in each, and what it says
        const interiors = {};
        for (const key of ['INT_TENT', 'INT_DORM', 'INT_FOREMAN']) {
            interiors[key] = (mapObjects[key] || []).map(o => ({ id: o.id, label: o.label, x: R(o.x), y: R(o.y), w: R(o.w), h: R(o.h), scene: o.interactScene || null, say: say(o.interactScene) }));
        }
        return {
            TILE_U, W: L.W, H: L.H, gw, gh, interiors,
            spawn: [R(player.x), R(player.y)],
            objects, walls,
            places: OW.places.map(q => ({ id: q.id, name: q.name, at: q.at, r: q.r })),
            rail: CH1_RAIL, railLoop: CH1_RAIL_LOOP,
            roads: CH1_SEGS.map(q => [R(q.x1), R(q.z1), R(q.x2), R(q.z2), R(q.hw), q.kind]),   // [x1, y1, x2, y2, half-width, kind (1 = driven road)]
            boundary: L.boundary, roadExits: L.roadExits, digRect: L.digRect, gateOpen: L.gateOpen, fenceZ: L.fenceZ, cliffZ: L.cliffZ, trench: CH1_TRENCH,
            grid: { hgt, path: path.join(''), rock: rock.join(''), wadi: wadi.join(''), out: out.join(''), dip: dip.join('') },
        };
    }, TILE_U);
    await b.close();
    fs.mkdirSync(path.join(ROOT, 'poke'), { recursive: true });
    const js = '// generated by tools/export_poke_map.js from the 3D build — do not edit\nwindow.POKE_MAP = ' + JSON.stringify(data) + ';\n';
    fs.writeFileSync(path.join(ROOT, 'poke', 'map_ch1.js'), js);
    console.log(`poke/map_ch1.js: ${data.gw}×${data.gh} tiles, ${data.objects.length} objects, ${data.walls.length} walls, ${data.objects.filter(o => o.say).length} with text, ${(js.length / 1024).toFixed(0)} KB`);
})().catch(e => { console.error('FAILED', e.message); process.exit(1); });
