// ============================================================
// PACK A PBR TEXTURE SET FOR THE GAME (tools/pack_texture.js)
// Browsers won't let WebGL use image files opened from file:// (a
// double-clicked index.html), so textures travel like the models do: as
// data URIs in a .js file. Takes an ambientCG / Poly Haven style folder
// (…_Color.jpg, …_NormalGL.jpg, …_Roughness.jpg, …_AmbientOcclusion.jpg),
// resizes and re-encodes each map, and writes textures/<name>.js:
//   window.CODEX_TEX[name] = { color, normal, rough, ao }   (data URIs)
//
//   node tools/pack_texture.js <name> <folder> [--size 1024] [--quality 82]
// Needs sharp (it comes with @gltf-transform/cli).
// ============================================================
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const a = process.argv.slice(2);
const name = a[0], dir = a[1];
const opt = (k, d) => { const i = a.indexOf('--' + k); return i >= 0 ? a[i + 1] : d; };
const size = +opt('size', 1024), quality = +opt('quality', 82);
if (!name || !dir) { console.error('usage: node tools/pack_texture.js <name> <folder> [--size 1024] [--quality 82]'); process.exit(1); }

const MAPS = { color: /_(Color|Albedo|Diffuse|BaseColor|diff)\./i, normal: /_(NormalGL|Normal_GL|nor_gl)\./i, rough: /_(Roughness|rough)\./i, ao: /_(AmbientOcclusion|AO)\./i };

(async () => {
    const files = fs.readdirSync(dir).filter(f => /\.(jpe?g|png)$/i.test(f));
    const out = {};
    let total = 0;
    for (const [k, re] of Object.entries(MAPS)) {
        const f = files.find(x => re.test(x));
        if (!f) continue;
        const buf = await sharp(path.join(dir, f)).resize(size, size, { fit: 'fill' }).jpeg({ quality, mozjpeg: true }).toBuffer();
        out[k] = 'data:image/jpeg;base64,' + buf.toString('base64');
        total += buf.length;
        console.log(`  ${k.padEnd(6)} ${f} → ${(buf.length / 1024).toFixed(0)} KB`);
    }
    if (!out.color) { console.error('no colour map found in ' + dir); process.exit(1); }
    fs.mkdirSync(path.join(ROOT, 'textures'), { recursive: true });
    fs.writeFileSync(path.join(ROOT, 'textures', name + '.js'), '// generated by tools/pack_texture.js — do not edit\n(window.CODEX_TEX = window.CODEX_TEX || {})[' + JSON.stringify(name) + '] = ' + JSON.stringify(out) + ';\n');
    console.log(`${name}: ${Object.keys(out).join(', ')}, ${(total / 1e6).toFixed(2)} MB → textures/${name}.js`);
})().catch(e => { console.error('FAILED', e.message); process.exit(1); });
