// ============================================================
// PREPARE A DOWNLOADED MODEL FOR THE GAME (tools/prepare_model.js)
// Uses glTF-Transform (npm i @gltf-transform/cli — brings core, functions,
// extensions, meshoptimizer, draco and sharp):
//   - optionally keeps just one piece of a pack (--keep NodeName)
//   - decodes Draco, welds, simplifies to a triangle budget while keeping
//     textures (meshoptimizer), resizes textures, drops unused data
//   - writes models/<name>.glb and models/<name>.js (base64, loads from
//     file:// and GitHub Pages alike)
//
//   node tools/prepare_model.js <name> <input.glb> [--keep Node] [--tris 8000] [--tex 1024]
// ============================================================
const fs = require('fs');
const path = require('path');
const { NodeIO } = require('@gltf-transform/core');
const { ALL_EXTENSIONS } = require('@gltf-transform/extensions');
const { weld, simplify, dedup, prune, textureCompress, flatten } = require('@gltf-transform/functions');
const { MeshoptSimplifier } = require('meshoptimizer');
const draco3d = require('draco3dgltf');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const a = process.argv.slice(2);
const name = a[0], input = a[1];
const opt = (k, d) => { const i = a.indexOf('--' + k); return i >= 0 ? a[i + 1] : d; };
const keep = opt('keep', null), tris = +opt('tris', 20000), tex = +opt('tex', 1024);
if (!name || !input) { console.error('usage: node tools/prepare_model.js <name> <input.glb> [--keep Node] [--tris 8000] [--tex 1024]'); process.exit(1); }

const countTris = (doc) => {
    let n = 0;
    for (const m of doc.getRoot().listMeshes()) for (const p of m.listPrimitives()) {
        const idx = p.getIndices();
        n += (idx ? idx.getCount() : p.getAttribute('POSITION').getCount()) / 3;
    }
    return Math.round(n);
};

(async () => {
    await MeshoptSimplifier.ready;
    const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({
        'draco3d.decoder': await draco3d.createDecoderModule(),
        'draco3d.encoder': await draco3d.createEncoderModule(),
    });
    const doc = await io.read(input);
    const root = doc.getRoot();
    if (keep) {
        const target = root.listNodes().find(n => n.getName() === keep);
        if (!target) { console.error('no node named ' + keep + '. Nodes: ' + root.listNodes().map(n => n.getName()).join(', ')); process.exit(1); }
        // the piece and everything under it (collected before flattening loses the hierarchy)
        const keepSet = new Set();
        const walk = n => { keepSet.add(n); n.listChildren().forEach(walk); };
        walk(target);
        await doc.transform(flatten());                        // world transforms onto every node, so a piece keeps its pose
        const sc0 = root.listScenes()[0];
        for (const sc of root.listScenes()) for (const ch of sc.listChildren()) sc.removeChild(ch);
        for (const n of root.listNodes()) {
            if (keepSet.has(n)) { if (n.getMesh()) sc0.addChild(n); }
            else n.dispose();
        }
    }
    // Draco-compressed input: drop the extension so the game never needs a decoder
    for (const ext of root.listExtensionsUsed()) if (/draco/i.test(ext.extensionName)) ext.dispose();
    await doc.transform(prune(), dedup(), weld());
    const before = countTris(doc);
    if (before > tris) await doc.transform(simplify({ simplifier: MeshoptSimplifier, ratio: Math.max(0.005, tris / before), error: 0.02 }));
    await doc.transform(textureCompress({ encoder: sharp, resize: [tex, tex], targetFormat: 'jpeg', quality: 82, pattern: /baseColor|diffuse|albedo|/i }), prune());
    const after = countTris(doc);
    const dir = path.join(ROOT, 'models');
    const glb = Buffer.from(await io.writeBinary(doc));
    fs.writeFileSync(path.join(dir, name + '.glb'), glb);
    fs.writeFileSync(path.join(dir, name + '.js'), '// generated by tools/prepare_model.js — do not edit\n(window.CODEX_MODELS = window.CODEX_MODELS || {})[' + JSON.stringify(name) + '] = "' + glb.toString('base64') + '";\n');
    console.log(`${name}: ${before.toLocaleString()} → ${after.toLocaleString()} tris, ${(glb.length / 1e6).toFixed(2)} MB → models/${name}.js`);
})().catch(e => { console.error('FAILED', e.message); process.exit(1); });
